version: '3'

services:
  ##############################
  ### SETUP SERVER CONTAINER ###
  ##############################
  backend:
    build:
      context: ./backend
    container_name: server
    expose:
      - 5000
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    volumes:
      - ./backend/src:/app/cnn/src
      - ./backend/src/image-tmp:/app/cnn/image-tmp
      - /etc/localtime:/etc/localtime:ro
    restart: always


  ##############################
  ### SETUP CLIENT CONTAINER ###
  ##############################
  client:
    build:
      context: ./client
    container_name: client
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - REACT_APP_PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASEURL=${BASEURL}
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
      - /etc/localtime:/etc/localtime:ro
    restart: always
    links:
      - server

  #############################
  ### SETUP NGINX CONTAINER ###
  #############################
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      -  /etc/localtime:/etc/localtime:ro
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 80:80
    links:
      - client
