version: '3'

services:

  ##############################
  ### SETUP CLIENT CONTAINER ###
  ##############################
  client:
    build:
      context: ./client
    container_name: client
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - REACT_APP_PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASEURL=${BASEURL}
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
      - /etc/localtime:/etc/localtime:ro
    restart: always
